In [91]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
from simulations import simulations as sim

# cerebellar ROIs
df1 = sim.y_sim()
df2 = sim.y_sim(seed = 9, region = 'region2')
df3 = sim.y_sim(seed = 99, region = 'region3')
df = pd.concat([df1, df2, df3], axis=0)

# tract ROIs
r1 = sim.y_sim(seed = 1, region = 'tract1')
r2 = sim.y_sim(seed = 2, region = 'tract2')
df = pd.concat([df, r1, r2], axis=0)
df = df*3

In [92]:
def _predict_roi_df(response_df, predict_df):
   # this will give a dataframe for each response_roi-week, you have vlaues of all weeks for each pred_roi
   predictors_df = predict_df.rename(columns = {'regionname': 'pred_region', 'mean': 'pred_mean', 'Week': 'pred_week'})
   roi_df = response_df.merge(predictors_df, on = 'subj_id', how = 'inner')


   return roi_df


response_df = pd.concat([df1, df2, df3], axis = 0)
predict_df = pd.concat([r1, r2], axis = 0)

roi_df = _predict_roi_df(response_df, predict_df)

In [93]:
models = {}
for pred_region in roi_df.pred_region.unique():
    for response_region in roi_df.regionname.unique():
        region_df = roi_df[(roi_df.pred_region == pred_region) & (roi_df.regionname == response_region)]
        model = smf.mixedlm("mean~0+ C(Week)*C(pred_week)*pred_mean", data = region_df, groups = region_df.subj_id).fit(maxiter = 400)
        models[(pred_region, response_region)] = model

To put in the weeks, we can just take the 'weeks' column from results_df and do a re search, where the first T. term is for the response, second is for the predictor.

In [94]:
def _results_df(model):

    fe = model.fe_params
    ci = model.conf_int().loc[fe.index]
    #se_vals = _se_vals(model)

    results = pd.DataFrame({
        'week': model.fe_params.index, # use re string search to get week num later
        'beta': model.fe_params.to_numpy(),
        'bse': model.bse_fe.to_numpy(),
        'converged': model.converged,
        't-val': model.tvalues.loc[fe.index].to_numpy(),
        'p-val': model.pvalues.loc[fe.index].to_numpy(),
        'ci_lower': ci[0].to_numpy(),
        'ci_upper': ci[1].to_numpy(),
        'log_likelihood': model.llf,
        #'se': se_vals
    })

    return results
model6 = models[(pred_region, response_region)]
results6 = _results_df(model6)

In [95]:
test = results6.iloc[23]['week']
pat = f'\d+'
res = re.findall(pat, test)
print(res)

['24', '52']

In [109]:
import re
pat = r'C\(Week\)\[T\.(\d+)\]' # put \ after char for literal
def _week_token(weeks_string, pat):
    week_vals = re.findall(pat, weeks_string)
    return week_vals

results6['resp_week'] = results6['week'].apply(lambda x:_week_token(x,pat))

In [110]:
results6

,week,beta,bse,converged,t-val,p-val,ci_lower,ci_upper,log_likelihood,resp_week
0,C(Week)[0],6.946067e+00,3.665270e-01,True,1.895104e+01,4.329625e-80,6.227687,7.664447,4374.179337,[]
1,C(Week)[4],1.094607e+01,3.665475e-01,True,2.986261e+01,6.021233e-196,10.227647,11.664487,4374.179337,[]
2,C(Week)[12],1.894607e+01,3.664717e-01,True,5.169858e+01,0.000000e+00,18.227796,19.664339,4374.179337,[]
3,C(Week)[24],3.094607e+01,3.665074e-01,True,8.443504e+01,0.000000e+00,30.227726,31.664409,4374.179337,[]
4,C(Week)[52],5.894607e+01,3.665573e-01,True,1.608100e+02,0.000000e+00,58.227628,59.664506,4374.179337,[]
5,C(pred_week)[T.4],3.375454e-01,2.476382e-01,True,1.363059e+00,1.728639e-01,-0.147816,0.822907,4374.179337,[]
6,C(pred_week)[T.12],1.012636e+00,7.429145e-01,True,1.363059e+00,1.728639e-01,-0.443449,2.468722,4374.179337,[]
7,C(pred_week)[T.24],2.025273e+00,1.485829e+00,True,1.363059e+00,1.728639e-01,-0.886899,4.937444,4374.179337,[]
8,C(pred_week)[T.52],4.388091e+00,3.219296e+00,True,1.363059e+00,1.728639e-01,-1.921614,10.697795,4374.179337,[]
9,C(Week)[T.4]:C(pred_week)[T.4],-2.257294e-13,8.554461e-06,True,-2.638733e-08,1.000000e+00,-0.000017,0.000017,4374.179337,[4]
10,C(Week)[T.12]:C(pred_week)[T.4],5.366270e-14,8.554461e-06,True,6.273066e-09,1.000000e+00,-0.000017,0.000017,4374.179337,[12]
11,C(Week)[T.24]:C(pred_week)[T.4],-3.332859e-14,8.554461e-06,True,-3.896048e-09,1.000000e+00,-0.000017,0.000017,4374.179337,[24]
12,C(Week)[T.52]:C(pred_week)[T.4],6.944491e-13,8.554461e-06,True,8.117976e-08,9.999999e-01,-0.000017,0.000017,4374.179337,[52]
13,C(Week)[T.4]:C(pred_week)[T.12],3.243127e-13,1.394367e-05,True,2.325878e-08,1.000000e+00,-0.000027,0.000027,4374.179337,[4]
14,C(Week)[T.12]:C(pred_week)[T.12],8.529024e-13,1.394367e-05,True,6.116771e-08,1.000000e+00,-0.000027,0.000027,4374.179337,[12]
15,C(Week)[T.24]:C(pred_week)[T.12],7.272338e-13,1.394367e-05,True,5.215512e-08,1.000000e+00,-0.000027,0.000027,4374.179337,[24]
16,C(Week)[T.52]:C(pred_week)[T.12],1.718144e-12,1.394367e-05,True,1.232204e-07,9.999999e-01,-0.000027,0.000027,4374.179337,[52]
17,C(Week)[T.4]:C(pred_week)[T.24],7.606535e-13,2.267826e-05,True,3.354109e-08,1.000000e+00,-0.000044,0.000044,4374.179337,[4]
18,C(Week)[T.12]:C(pred_week)[T.24],1.221591e-12,2.267826e-05,True,5.386618e-08,1.000000e+00,-0.000044,0.000044,4374.179337,[12]
19,C(Week)[T.24]:C(pred_week)[T.24],3.682048e-13,2.267826e-05,True,1.623602e-08,1.000000e+00,-0.000044,0.000044,4374.179337,[24]
20,C(Week)[T.52]:C(pred_week)[T.24],7.695995e-13,2.267826e-05,True,3.393556e-08,1.000000e+00,-0.000044,0.000044,4374.179337,[52]
21,C(Week)[T.4]:C(pred_week)[T.52],-1.544302e-12,4.364306e-05,True,-3.538483e-08,1.000000e+00,-0.000086,0.000086,4374.179337,[4]
22,C(Week)[T.12]:C(pred_week)[T.52],4.918563e-13,4.364306e-05,True,1.126998e-08,1.000000e+00,-0.000086,0.000086,4374.179337,[12]
23,C(Week)[T.24]:C(pred_week)[T.52],-1.283593e-12,4.364306e-05,True,-2.941115e-08,1.000000e+00,-0.000086,0.000086,4374.179337,[24]
24,C(Week)[T.52]:C(pred_week)[T.52],-5.897755e-13,4.364306e-05,True,-1.351362e-08,1.000000e+00,-0.000086,0.000086,4374.179337,[52]
25,pred_mean,-8.438636e-02,6.190954e-02,True,-1.363059e+00,1.728639e-01,-0.205727,0.036954,4374.179337,[]
26,C(Week)[T.4]:pred_mean,-1.175034e-13,7.583063e-07,True,-1.549551e-07,9.999999e-01,-0.000001,0.000001,4374.179337,[4]
27,C(Week)[T.12]:pred_mean,-6.574890e-14,7.583063e-07,True,-8.670494e-08,9.999999e-01,-0.000001,0.000001,4374.179337,[12]
28,C(Week)[T.24]:pred_mean,-8.180824e-14,7.583063e-07,True,-1.078828e-07,9.999999e-01,-0.000001,0.000001,4374.179337,[24]
29,C(Week)[T.52]:pred_mean,2.078299e-14,7.583063e-07,True,2.740712e-08,1.000000e+00,-0.000001,0.000001,4374.179337,[52]
30,C(pred_week)[T.4]:pred_mean,-6.332591e-14,7.583063e-07,True,-8.350967e-08,9.999999e-01,-0.000001,0.000001,4374.179337,[]
31,C(pred_week)[T.12]:pred_mean,-3.951329e-14,7.583063e-07,True,-5.210729e-08,1.000000e+00,-0.000001,0.000001,4374.179337,[]
32,C(pred_week)[T.24]:pred_mean,-5.809170e-14,7.583063e-07,True,-7.660717e-08,9.999999e-01,-0.000001,0.000001,4374.179337,[]
33,C(pred_week)[T.52]:pred_mean,-8.662052e-14,7.583063e-07,True,-1.142289e-07,9.999999e-01,-0.000001,0.000001,4374.179337,[]
34,C(Week)[T.4]:C(pred_week)[T.4]:pred_mean,8.734998e-14,1.072407e-06,True,8.145226e-08,9.999999e-01,-0.000002,0.000002,4374.179337,[4]
35,C(Week)[T.12]:C(pred_week)[T.4]:pred_mean,3.520622e-14,1.072407e-06,True,3.282916e-08,1.000000e+00,-0.000002,0.000002,4374.179337,[12]
36,C(Week)[T.24]:C(pred_week)[T.4]:pred_mean,5.208608e-14,1.072407e-06,True,4.856932e-08,1.000000e+00,-0.000002,0.000002,4374.179337,[24]
37,C(Week)[T.52]:C(pred_week)[T.4]:pred_mean,-6.205754e-14,1.072407e-06,True,-5.786752e-08,1.000000e+00,-0.000002,0.000002,4374.179337,[52]
38,C(Week)[T.4]:C(pred_week)[T.12]:pred_mean,6.940795e-14,1.072407e-06,True,6.472164e-08,9.999999e-01,-0.000002,0.000002,4374.179337,[4]
39,C(Week)[T.12]:C(pred_week)[T.12]:pred_mean,2.987869e-15,1.072407e-06,True,2.786133e-09,1.000000e+00,-0.000002,0.000002,4374.179337,[12]
40,C(Week)[T.24]:C(pred_week)[T.12]:pred_mean,2.173712e-14,1.072407e-06,True,2.026947e-08,1.000000e+00,-0.000002,0.000002,4374.179337,[24]
41,C(Week)[T.52]:C(pred_week)[T.12]:pred_mean,-1.023442e-13,1.072407e-06,True,-9.543408e-08,9.999999e-01,-0.000002,0.000002,4374.179337,[52]
42,C(Week)[T.4]:C(pred_week)[T.24]:pred_mean,7.440108e-14,1.072407e-06,True,6.937765e-08,9.999999e-01,-0.000002,0.000002,4374.179337,[4]
43,C(Week)[T.12]:C(pred_week)[T.24]:pred_mean,1.632173e-14,1.072407e-06,True,1.521971e-08,1.000000e+00,-0.000002,0.000002,4374.179337,[12]
44,C(Week)[T.24]:C(pred_week)[T.24]:pred_mean,5.890503e-14,1.072407e-06,True,5.492786e-08,1.000000e+00,-0.000002,0.000002,4374.179337,[24]
45,C(Week)[T.52]:C(pred_week)[T.24]:pred_mean,-3.613436e-14,1.072407e-06,True,-3.369463e-08,1.000000e+00,-0.000002,0.000002,4374.179337,[52]
46,C(Week)[T.4]:C(pred_week)[T.52]:pred_mean,1.358101e-13,1.072407e-06,True,1.266405e-07,9.999999e-01,-0.000002,0.000002,4374.179337,[4]
47,C(Week)[T.12]:C(pred_week)[T.52]:pred_mean,5.328086e-14,1.072407e-06,True,4.968343e-08,1.000000e+00,-0.000002,0.000002,4374.179337,[12]
48,C(Week)[T.24]:C(pred_week)[T.52]:pred_mean,9.900167e-14,1.072407e-06,True,9.231725e-08,9.999999e-01,-0.000002,0.000002,4374.179337,[24]
49,C(Week)[T.52]:C(pred_week)[T.52]:pred_mean,-4.945649e-15,1.072407e-06,True,-4.611727e-09,1.000000e+00,-0.000002,0.000002,4374.179337,[52]

In [ ]:
results6['resp_week'] = results6['week'].apply(_week_token)

SyntaxError: incomplete input (3671139620.py, line 1)

In [ ]:
results6

,week,beta,bse,converged,t-val,p-val,ci_lower,ci_upper,log_likelihood,resp_week
0,C(Week)[0],6.946067e+00,3.665270e-01,True,1.895104e+01,4.329625e-80,6.227687,7.664447,4374.179337,[]
1,C(Week)[4],1.094607e+01,3.665475e-01,True,2.986261e+01,6.021233e-196,10.227647,11.664487,4374.179337,[]
2,C(Week)[12],1.894607e+01,3.664717e-01,True,5.169858e+01,0.000000e+00,18.227796,19.664339,4374.179337,[]
3,C(Week)[24],3.094607e+01,3.665074e-01,True,8.443504e+01,0.000000e+00,30.227726,31.664409,4374.179337,[]
4,C(Week)[52],5.894607e+01,3.665573e-01,True,1.608100e+02,0.000000e+00,58.227628,59.664506,4374.179337,[]
5,C(pred_week)[T.4],3.375454e-01,2.476382e-01,True,1.363059e+00,1.728639e-01,-0.147816,0.822907,4374.179337,[]
6,C(pred_week)[T.12],1.012636e+00,7.429145e-01,True,1.363059e+00,1.728639e-01,-0.443449,2.468722,4374.179337,[]
7,C(pred_week)[T.24],2.025273e+00,1.485829e+00,True,1.363059e+00,1.728639e-01,-0.886899,4.937444,4374.179337,[]
8,C(pred_week)[T.52],4.388091e+00,3.219296e+00,True,1.363059e+00,1.728639e-01,-1.921614,10.697795,4374.179337,[]
9,C(Week)[T.4]:C(pred_week)[T.4],-2.257294e-13,8.554461e-06,True,-2.638733e-08,1.000000e+00,-0.000017,0.000017,4374.179337,[4]
10,C(Week)[T.12]:C(pred_week)[T.4],5.366270e-14,8.554461e-06,True,6.273066e-09,1.000000e+00,-0.000017,0.000017,4374.179337,[12]
11,C(Week)[T.24]:C(pred_week)[T.4],-3.332859e-14,8.554461e-06,True,-3.896048e-09,1.000000e+00,-0.000017,0.000017,4374.179337,[24]
12,C(Week)[T.52]:C(pred_week)[T.4],6.944491e-13,8.554461e-06,True,8.117976e-08,9.999999e-01,-0.000017,0.000017,4374.179337,[52]
13,C(Week)[T.4]:C(pred_week)[T.12],3.243127e-13,1.394367e-05,True,2.325878e-08,1.000000e+00,-0.000027,0.000027,4374.179337,[4]
14,C(Week)[T.12]:C(pred_week)[T.12],8.529024e-13,1.394367e-05,True,6.116771e-08,1.000000e+00,-0.000027,0.000027,4374.179337,[12]
15,C(Week)[T.24]:C(pred_week)[T.12],7.272338e-13,1.394367e-05,True,5.215512e-08,1.000000e+00,-0.000027,0.000027,4374.179337,[24]
16,C(Week)[T.52]:C(pred_week)[T.12],1.718144e-12,1.394367e-05,True,1.232204e-07,9.999999e-01,-0.000027,0.000027,4374.179337,[52]
17,C(Week)[T.4]:C(pred_week)[T.24],7.606535e-13,2.267826e-05,True,3.354109e-08,1.000000e+00,-0.000044,0.000044,4374.179337,[4]
18,C(Week)[T.12]:C(pred_week)[T.24],1.221591e-12,2.267826e-05,True,5.386618e-08,1.000000e+00,-0.000044,0.000044,4374.179337,[12]
19,C(Week)[T.24]:C(pred_week)[T.24],3.682048e-13,2.267826e-05,True,1.623602e-08,1.000000e+00,-0.000044,0.000044,4374.179337,[24]
20,C(Week)[T.52]:C(pred_week)[T.24],7.695995e-13,2.267826e-05,True,3.393556e-08,1.000000e+00,-0.000044,0.000044,4374.179337,[52]
21,C(Week)[T.4]:C(pred_week)[T.52],-1.544302e-12,4.364306e-05,True,-3.538483e-08,1.000000e+00,-0.000086,0.000086,4374.179337,[4]
22,C(Week)[T.12]:C(pred_week)[T.52],4.918563e-13,4.364306e-05,True,1.126998e-08,1.000000e+00,-0.000086,0.000086,4374.179337,[12]
23,C(Week)[T.24]:C(pred_week)[T.52],-1.283593e-12,4.364306e-05,True,-2.941115e-08,1.000000e+00,-0.000086,0.000086,4374.179337,[24]
24,C(Week)[T.52]:C(pred_week)[T.52],-5.897755e-13,4.364306e-05,True,-1.351362e-08,1.000000e+00,-0.000086,0.000086,4374.179337,[52]
25,pred_mean,-8.438636e-02,6.190954e-02,True,-1.363059e+00,1.728639e-01,-0.205727,0.036954,4374.179337,[]
26,C(Week)[T.4]:pred_mean,-1.175034e-13,7.583063e-07,True,-1.549551e-07,9.999999e-01,-0.000001,0.000001,4374.179337,[4]
27,C(Week)[T.12]:pred_mean,-6.574890e-14,7.583063e-07,True,-8.670494e-08,9.999999e-01,-0.000001,0.000001,4374.179337,[12]
28,C(Week)[T.24]:pred_mean,-8.180824e-14,7.583063e-07,True,-1.078828e-07,9.999999e-01,-0.000001,0.000001,4374.179337,[24]
29,C(Week)[T.52]:pred_mean,2.078299e-14,7.583063e-07,True,2.740712e-08,1.000000e+00,-0.000001,0.000001,4374.179337,[52]
30,C(pred_week)[T.4]:pred_mean,-6.332591e-14,7.583063e-07,True,-8.350967e-08,9.999999e-01,-0.000001,0.000001,4374.179337,[]
31,C(pred_week)[T.12]:pred_mean,-3.951329e-14,7.583063e-07,True,-5.210729e-08,1.000000e+00,-0.000001,0.000001,4374.179337,[]
32,C(pred_week)[T.24]:pred_mean,-5.809170e-14,7.583063e-07,True,-7.660717e-08,9.999999e-01,-0.000001,0.000001,4374.179337,[]
33,C(pred_week)[T.52]:pred_mean,-8.662052e-14,7.583063e-07,True,-1.142289e-07,9.999999e-01,-0.000001,0.000001,4374.179337,[]
34,C(Week)[T.4]:C(pred_week)[T.4]:pred_mean,8.734998e-14,1.072407e-06,True,8.145226e-08,9.999999e-01,-0.000002,0.000002,4374.179337,[4]
35,C(Week)[T.12]:C(pred_week)[T.4]:pred_mean,3.520622e-14,1.072407e-06,True,3.282916e-08,1.000000e+00,-0.000002,0.000002,4374.179337,[12]
36,C(Week)[T.24]:C(pred_week)[T.4]:pred_mean,5.208608e-14,1.072407e-06,True,4.856932e-08,1.000000e+00,-0.000002,0.000002,4374.179337,[24]
37,C(Week)[T.52]:C(pred_week)[T.4]:pred_mean,-6.205754e-14,1.072407e-06,True,-5.786752e-08,1.000000e+00,-0.000002,0.000002,4374.179337,[52]
38,C(Week)[T.4]:C(pred_week)[T.12]:pred_mean,6.940795e-14,1.072407e-06,True,6.472164e-08,9.999999e-01,-0.000002,0.000002,4374.179337,[4]
39,C(Week)[T.12]:C(pred_week)[T.12]:pred_mean,2.987869e-15,1.072407e-06,True,2.786133e-09,1.000000e+00,-0.000002,0.000002,4374.179337,[12]
40,C(Week)[T.24]:C(pred_week)[T.12]:pred_mean,2.173712e-14,1.072407e-06,True,2.026947e-08,1.000000e+00,-0.000002,0.000002,4374.179337,[24]
41,C(Week)[T.52]:C(pred_week)[T.12]:pred_mean,-1.023442e-13,1.072407e-06,True,-9.543408e-08,9.999999e-01,-0.000002,0.000002,4374.179337,[52]
42,C(Week)[T.4]:C(pred_week)[T.24]:pred_mean,7.440108e-14,1.072407e-06,True,6.937765e-08,9.999999e-01,-0.000002,0.000002,4374.179337,[4]
43,C(Week)[T.12]:C(pred_week)[T.24]:pred_mean,1.632173e-14,1.072407e-06,True,1.521971e-08,1.000000e+00,-0.000002,0.000002,4374.179337,[12]
44,C(Week)[T.24]:C(pred_week)[T.24]:pred_mean,5.890503e-14,1.072407e-06,True,5.492786e-08,1.000000e+00,-0.000002,0.000002,4374.179337,[24]
45,C(Week)[T.52]:C(pred_week)[T.24]:pred_mean,-3.613436e-14,1.072407e-06,True,-3.369463e-08,1.000000e+00,-0.000002,0.000002,4374.179337,[52]
46,C(Week)[T.4]:C(pred_week)[T.52]:pred_mean,1.358101e-13,1.072407e-06,True,1.266405e-07,9.999999e-01,-0.000002,0.000002,4374.179337,[4]
47,C(Week)[T.12]:C(pred_week)[T.52]:pred_mean,5.328086e-14,1.072407e-06,True,4.968343e-08,1.000000e+00,-0.000002,0.000002,4374.179337,[12]
48,C(Week)[T.24]:C(pred_week)[T.52]:pred_mean,9.900167e-14,1.072407e-06,True,9.231725e-08,9.999999e-01,-0.000002,0.000002,4374.179337,[24]
49,C(Week)[T.52]:C(pred_week)[T.52]:pred_mean,-4.945649e-15,1.072407e-06,True,-4.611727e-09,1.000000e+00,-0.000002,0.000002,4374.179337,[52]

In [ ]:
C\(Week\)\[T\.(\d+)\]

In [ ]:
test = results6.iloc[23]['week']
pat = r'C\(Week\)\[T\.(\d+)\]' # put \ after char for literal
res = re.findall(pat, test)
print(res)

['24']

In [ ]:
results6

,week,beta,bse,converged,t-val,p-val,ci_lower,ci_upper,log_likelihood
0,C(Week)[0],6.946067e+00,3.665270e-01,True,1.895104e+01,4.329625e-80,6.227687,7.664447,4374.179337
1,C(Week)[4],1.094607e+01,3.665475e-01,True,2.986261e+01,6.021233e-196,10.227647,11.664487,4374.179337
2,C(Week)[12],1.894607e+01,3.664717e-01,True,5.169858e+01,0.000000e+00,18.227796,19.664339,4374.179337
3,C(Week)[24],3.094607e+01,3.665074e-01,True,8.443504e+01,0.000000e+00,30.227726,31.664409,4374.179337
4,C(Week)[52],5.894607e+01,3.665573e-01,True,1.608100e+02,0.000000e+00,58.227628,59.664506,4374.179337
5,C(pred_week)[T.4],3.375454e-01,2.476382e-01,True,1.363059e+00,1.728639e-01,-0.147816,0.822907,4374.179337
6,C(pred_week)[T.12],1.012636e+00,7.429145e-01,True,1.363059e+00,1.728639e-01,-0.443449,2.468722,4374.179337
7,C(pred_week)[T.24],2.025273e+00,1.485829e+00,True,1.363059e+00,1.728639e-01,-0.886899,4.937444,4374.179337
8,C(pred_week)[T.52],4.388091e+00,3.219296e+00,True,1.363059e+00,1.728639e-01,-1.921614,10.697795,4374.179337
9,C(Week)[T.4]:C(pred_week)[T.4],-2.257294e-13,8.554461e-06,True,-2.638733e-08,1.000000e+00,-0.000017,0.000017,4374.179337
10,C(Week)[T.12]:C(pred_week)[T.4],5.366270e-14,8.554461e-06,True,6.273066e-09,1.000000e+00,-0.000017,0.000017,4374.179337
11,C(Week)[T.24]:C(pred_week)[T.4],-3.332859e-14,8.554461e-06,True,-3.896048e-09,1.000000e+00,-0.000017,0.000017,4374.179337
12,C(Week)[T.52]:C(pred_week)[T.4],6.944491e-13,8.554461e-06,True,8.117976e-08,9.999999e-01,-0.000017,0.000017,4374.179337
13,C(Week)[T.4]:C(pred_week)[T.12],3.243127e-13,1.394367e-05,True,2.325878e-08,1.000000e+00,-0.000027,0.000027,4374.179337
14,C(Week)[T.12]:C(pred_week)[T.12],8.529024e-13,1.394367e-05,True,6.116771e-08,1.000000e+00,-0.000027,0.000027,4374.179337
15,C(Week)[T.24]:C(pred_week)[T.12],7.272338e-13,1.394367e-05,True,5.215512e-08,1.000000e+00,-0.000027,0.000027,4374.179337
16,C(Week)[T.52]:C(pred_week)[T.12],1.718144e-12,1.394367e-05,True,1.232204e-07,9.999999e-01,-0.000027,0.000027,4374.179337
17,C(Week)[T.4]:C(pred_week)[T.24],7.606535e-13,2.267826e-05,True,3.354109e-08,1.000000e+00,-0.000044,0.000044,4374.179337
18,C(Week)[T.12]:C(pred_week)[T.24],1.221591e-12,2.267826e-05,True,5.386618e-08,1.000000e+00,-0.000044,0.000044,4374.179337
19,C(Week)[T.24]:C(pred_week)[T.24],3.682048e-13,2.267826e-05,True,1.623602e-08,1.000000e+00,-0.000044,0.000044,4374.179337
20,C(Week)[T.52]:C(pred_week)[T.24],7.695995e-13,2.267826e-05,True,3.393556e-08,1.000000e+00,-0.000044,0.000044,4374.179337
21,C(Week)[T.4]:C(pred_week)[T.52],-1.544302e-12,4.364306e-05,True,-3.538483e-08,1.000000e+00,-0.000086,0.000086,4374.179337
22,C(Week)[T.12]:C(pred_week)[T.52],4.918563e-13,4.364306e-05,True,1.126998e-08,1.000000e+00,-0.000086,0.000086,4374.179337
23,C(Week)[T.24]:C(pred_week)[T.52],-1.283593e-12,4.364306e-05,True,-2.941115e-08,1.000000e+00,-0.000086,0.000086,4374.179337
24,C(Week)[T.52]:C(pred_week)[T.52],-5.897755e-13,4.364306e-05,True,-1.351362e-08,1.000000e+00,-0.000086,0.000086,4374.179337
25,pred_mean,-8.438636e-02,6.190954e-02,True,-1.363059e+00,1.728639e-01,-0.205727,0.036954,4374.179337
26,C(Week)[T.4]:pred_mean,-1.175034e-13,7.583063e-07,True,-1.549551e-07,9.999999e-01,-0.000001,0.000001,4374.179337
27,C(Week)[T.12]:pred_mean,-6.574890e-14,7.583063e-07,True,-8.670494e-08,9.999999e-01,-0.000001,0.000001,4374.179337
28,C(Week)[T.24]:pred_mean,-8.180824e-14,7.583063e-07,True,-1.078828e-07,9.999999e-01,-0.000001,0.000001,4374.179337
29,C(Week)[T.52]:pred_mean,2.078299e-14,7.583063e-07,True,2.740712e-08,1.000000e+00,-0.000001,0.000001,4374.179337
30,C(pred_week)[T.4]:pred_mean,-6.332591e-14,7.583063e-07,True,-8.350967e-08,9.999999e-01,-0.000001,0.000001,4374.179337
31,C(pred_week)[T.12]:pred_mean,-3.951329e-14,7.583063e-07,True,-5.210729e-08,1.000000e+00,-0.000001,0.000001,4374.179337
32,C(pred_week)[T.24]:pred_mean,-5.809170e-14,7.583063e-07,True,-7.660717e-08,9.999999e-01,-0.000001,0.000001,4374.179337
33,C(pred_week)[T.52]:pred_mean,-8.662052e-14,7.583063e-07,True,-1.142289e-07,9.999999e-01,-0.000001,0.000001,4374.179337
34,C(Week)[T.4]:C(pred_week)[T.4]:pred_mean,8.734998e-14,1.072407e-06,True,8.145226e-08,9.999999e-01,-0.000002,0.000002,4374.179337
35,C(Week)[T.12]:C(pred_week)[T.4]:pred_mean,3.520622e-14,1.072407e-06,True,3.282916e-08,1.000000e+00,-0.000002,0.000002,4374.179337
36,C(Week)[T.24]:C(pred_week)[T.4]:pred_mean,5.208608e-14,1.072407e-06,True,4.856932e-08,1.000000e+00,-0.000002,0.000002,4374.179337
37,C(Week)[T.52]:C(pred_week)[T.4]:pred_mean,-6.205754e-14,1.072407e-06,True,-5.786752e-08,1.000000e+00,-0.000002,0.000002,4374.179337
38,C(Week)[T.4]:C(pred_week)[T.12]:pred_mean,6.940795e-14,1.072407e-06,True,6.472164e-08,9.999999e-01,-0.000002,0.000002,4374.179337
39,C(Week)[T.12]:C(pred_week)[T.12]:pred_mean,2.987869e-15,1.072407e-06,True,2.786133e-09,1.000000e+00,-0.000002,0.000002,4374.179337
40,C(Week)[T.24]:C(pred_week)[T.12]:pred_mean,2.173712e-14,1.072407e-06,True,2.026947e-08,1.000000e+00,-0.000002,0.000002,4374.179337
41,C(Week)[T.52]:C(pred_week)[T.12]:pred_mean,-1.023442e-13,1.072407e-06,True,-9.543408e-08,9.999999e-01,-0.000002,0.000002,4374.179337
42,C(Week)[T.4]:C(pred_week)[T.24]:pred_mean,7.440108e-14,1.072407e-06,True,6.937765e-08,9.999999e-01,-0.000002,0.000002,4374.179337
43,C(Week)[T.12]:C(pred_week)[T.24]:pred_mean,1.632173e-14,1.072407e-06,True,1.521971e-08,1.000000e+00,-0.000002,0.000002,4374.179337
44,C(Week)[T.24]:C(pred_week)[T.24]:pred_mean,5.890503e-14,1.072407e-06,True,5.492786e-08,1.000000e+00,-0.000002,0.000002,4374.179337
45,C(Week)[T.52]:C(pred_week)[T.24]:pred_mean,-3.613436e-14,1.072407e-06,True,-3.369463e-08,1.000000e+00,-0.000002,0.000002,4374.179337
46,C(Week)[T.4]:C(pred_week)[T.52]:pred_mean,1.358101e-13,1.072407e-06,True,1.266405e-07,9.999999e-01,-0.000002,0.000002,4374.179337
47,C(Week)[T.12]:C(pred_week)[T.52]:pred_mean,5.328086e-14,1.072407e-06,True,4.968343e-08,1.000000e+00,-0.000002,0.000002,4374.179337
48,C(Week)[T.24]:C(pred_week)[T.52]:pred_mean,9.900167e-14,1.072407e-06,True,9.231725e-08,9.999999e-01,-0.000002,0.000002,4374.179337
49,C(Week)[T.52]:C(pred_week)[T.52]:pred_mean,-4.945649e-15,1.072407e-06,True,-4.611727e-09,1.000000e+00,-0.000002,0.000002,4374.179337

In [ ]:
results6['pred_week'] = results6['week']

'C(Week)[0]'

In [ ]:
results6.iloc[0]['week']

'C(Week)[0]'

In [ ]:
week_val

'C(Week)[0]'

how do we sum up the betas here?